version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openai-agent
    restart: always
    ports:
      - "3000:3000"
    working_dir: /app/
    command: ["npm", "start","--prefix","/app/openai-realtime-agents"]
